import { Building2, DoorOpen, Plane, PlaneLanding } from "lucide-react";
import { StatusBadge } from "@/components/ui/status-badge";
import type { Flight } from "@/lib/airport-config";

export function FlightCard({ flight }: { flight: Flight }) {
  const departure = flight.kind === "departure";
  const LocationIcon = departure ? DoorOpen : PlaneLanding;
  return <article className="glass-panel glass-panel-hover group rounded-2xl border border-white/10 p-5 transition-all hover:border-cyan-400/40"><div className="mb-4 flex items-start justify-between border-b border-white/10 pb-3"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-full border border-white/20 bg-white/10 p-2">{departure ? <Plane className="size-5 -rotate-45 text-[#00d2ff]" /> : <PlaneLanding className="size-5 text-[#00d2ff]" />}</div><div><h3 className="font-display text-lg font-bold text-white group-hover:text-[#00d2ff]">{flight.route}</h3><p className="font-mono text-xs tracking-wider text-slate-400">{flight.code} • Maskapai berjadwal</p></div></div><StatusBadge status={flight.status} /></div><div className="grid grid-cols-3 gap-4 text-center sm:text-left"><div><p className="mb-1 font-mono text-[11px] uppercase text-slate-400">{flight.oldTime ? "Est. Time" : "Scheduled"}</p><p className={`font-display text-xl font-bold ${flight.status === "Tertunda" ? "text-amber-400" : "text-white"}`}>{flight.time} {flight.oldTime && <span className="font-mono text-xs text-slate-500 line-through">{flight.oldTime}</span>}</p></div><div><p className="mb-1 font-mono text-[11px] uppercase text-slate-400">Terminal</p><p className="font-display flex items-center justify-center gap-1 text-sm font-bold text-white sm:justify-start sm:text-xl"><Building2 className="size-4 text-[#00d2ff]" />{departure ? "Keberangkatan" : "Kedatangan"}</p></div><div><p className="mb-1 font-mono text-[11px] uppercase text-slate-400">{flight.locationLabel}</p><p className="font-display flex items-center justify-center gap-1 text-sm font-bold text-[#00d2ff] sm:justify-start sm:text-xl"><LocationIcon className="size-4" />{flight.location}</p></div></div></article>;
}
